"""Methane (LNG) thermophysical property surrogates.

Mirrors the public API of :class:`hytank.H2_properties.HydrogenProperties`
so the existing physics components in ``boil_off.py`` keep working
unchanged when methane is selected as the propellant.

The surrogate methods are inherited from ``HydrogenProperties`` and
keep their original ``lh2_*`` / ``gh2_*`` / ``sat_gh2_*`` names — they
read out of ``self.sat_surrogates`` / ``self.gas_surrogates`` whose
keys are name-bound, not propellant-bound, so the existing call sites
in HyTank's components are propellant-agnostic by construction.

Property data is generated by
``hytank.CH4_property_data.generate_from_coolprop`` and loaded through
``hytank.CH4_property_data.data_parser`` (which is API-compatible with
the H2 parser).
"""

from hytank.H2_properties import HydrogenProperties
from hytank.CH4_property_data.data_parser import get_sat_property, get_property
from hytank.utilities.constants import MOLEC_WEIGHT_CH4


class MethaneProperties(HydrogenProperties):
    """Methane (CH4 / LNG) property surrogate models.

    Identical interface to :class:`HydrogenProperties` (same method
    names, same return units, same surrogate behavior); only the
    underlying data and molecular weight differ.

    Surrogates are trained from the tab-separated NIST-schema files in
    ``hytank/CH4_property_data/`` on first instantiation and cached as
    pickle files in that directory. Delete the cache files to retrain
    after editing the source data.
    """

    MOLEC_WEIGHT = MOLEC_WEIGHT_CH4  # kg/mol, molecular weight of methane

    _data_subdir = "CH4_property_data"
    _get_sat_property = staticmethod(get_sat_property)
    _get_property = staticmethod(get_property)
